/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ken.mizoguch.gcodefx;

/**
 *
 * @author mizoguch-ken
 */
public enum DesignEnums {
    CONTROLLER("Controller"),
    EDITOR("Editor"),
    ACE_EDITOR("AceEditor"),
    GCODE_INTERPRETER("GcodeInterpreter"),
    GCODE_VIRTUAL_MACHINE("GcodeVirtualMachine"),
    SERIAL("Serial"),
    JAVA_LIBRARY("JavaLibrary"),
    FILE("File", "ファイル"),
    FILE_NEW("New", "新規作成"),
    FILE_OPEN("Open", "開く"),
    FILE_SAVE("Save", "上書き保存"),
    FILE_SAVE_AS("Save As..", "名前を付けて保存"),
    FILE_NEXT_GENERATION_CONTROLLER("ngc"),
    FILE_GCODE_BYTE_CODE("gbc"),
    VIEW("View", "表示"),
    VIEW_CONTROL_PANEL("Control Panel", "コントロールパネル"),
    VIEW_CONSOLE("Console", "コンソール"),
    EXTENSION("Extension", "拡張"),
    EXTENSION＿WEB("Web", "ウェブ"),
    EXTENSION＿LADDER("Ladder", "ラダー"),
    SETTINGS("Settings", "設定"),
    HELP("Help", "ヘルプ"),
    HELP_LANGUAGE("言語", "Language"),
    HELP_SHOW_LICENSES("Licenses", "ライセンス"),
    HELP_SHOW_VERSION("Version", "バージョン"),
    PROGRAM("Program", "プログラム"),
    PROGRAM_NUMBER_TIP("empty: normal transmission \n Program Number: Run sending the program number in the virtual machine", "空白: 通常送信\nプログラム番号: プログラム番号を仮想マシンで実行送信"),
    OPTIONAL_SKIP0("/"),
    OPTIONAL_SKIP2("/2"),
    OPTIONAL_SKIP3("/3"),
    OPTIONAL_SKIP4("/4"),
    OPTIONAL_SKIP5("/5"),
    OPTIONAL_SKIP6("/6"),
    OPTIONAL_SKIP7("/7"),
    OPTIONAL_SKIP8("/8"),
    OPTIONAL_SKIP9("/9"),
    OPTIONAL_SKIP_TIP("Optional block skip \n ※ only run in a virtual machine", "オプショナルブロックスキップ\n※仮想マシン内でのみ実行"),
    ADD_EDITOR("Add Editor", "エディタ追加"),
    BASE("Base", "基本"),
    VIRTUAL_MACHINE("Virtual Machine", "仮想マシン"),
    VIRTUAL_MACHINE_NAME_TIP("Virtual machine name", "仮想マシン名"),
    VIRTUAL_MACHINE_LOAD("Load", "読込"),
    VIRTUAL_MACHINE_LOAD_TIP("Load virtual machine settings", "仮想マシン設定の読込"),
    VIRTUAL_MACHINE_SAVE("Save", "保存"),
    VIRTUAL_MACHINE_SAVE_TIP("Save virtual machine settings", "仮想マシン設定の保存"),
    LOG("Log", "ログ"),
    LOG_TIP("To record a log", "ログを記録する"),
    DEBUG("Debug", "デバッグ"),
    DEBUG_TIP("Output debug", "デバッグを出力する"),
    SERIAL_PORT("Serial Port", "シリアルポート"),
    SERIAL_PORT_TIP("Serial port", "シリアルポート"),
    SERIAL_PORT_LIST("List", "リスト"),
    SERIAL_PORT_LIST_TIP("Serial Port List", "シリアルポート一覧"),
    SERIAL_CONNECT("Connect", "接続"),
    SERIAL_CONNECT_TIP("Connect serial communication", "シリアル通信の接続"),
    SERIAL_DISCONNECT("Disconnect", "切断"),
    SERIAL_DISCONNECT_TIP("Disconnect serial communication", "シリアル通信の切断"),
    SERIAL_CHARACTER("1 character send", "1文字送信"),
    SERIAL_CHARACTER_TIP("To transmit one character at a time", "１文字ずつ送信を行う"),
    SERIAL_OBSERVE_CTS("CTS Status Monitor", "CTS状態監視"),
    SERIAL_OBSERVE_CTS_TIP("CTS Monitor the connection status", "CTS接続状態を監視"),
    SERIAL_OBSERVE_DSR("DSR Status Monitor", "DSR状態監視"),
    SERIAL_OBSERVE_DSR_TIP("DSR Monitor the connection status", "DSR接続状態を監視"),
    SERIAL_OBSERVE_DC2DC4("DC2/DC4 Status Monitor", "DC2/DC4状態監視"),
    SERIAL_OBSERVE_DC2DC4_TIP("DC2/DC4 Monitor the connection status", "DC2/DC4接続状態を監視"),
    SERIAL_BAUDRATE("Baudrate", "通信速度"),
    SERIAL_BAUDRATE_TIP("Serial baudrate", "シリアル通信速度"),
    SERIAL_DATA_BITS("Data Bits", "データビット"),
    SERIAL_DATA_BITS_TIP("Serial data bits", "シリアルデータビット"),
    SERIAL_STOP_BITS("Stop Bits", "ストップビット"),
    SERIAL_STOP_BITS_TIP("Serial stop bits", "シリアルストップビット"),
    SERIAL_PARITY("Parity", "パリティ"),
    SERIAL_PARITY_TIP("Serial parity", "シリアルパリティ"),
    SERIAL_EOB("EOB"),
    SERIAL_EOB_TIP("Serial EOB", "シリアル EOB"),
    SERIAL_BUFFER_LIMIT("Buffer Limit", "バッファリミット"),
    SERIAL_BUFFER_LIMIT_TIP("Serial transmission, the upper limit of the number of blocks to be held in the buffer", "シリアル送信時、バッファに保持するブロック数の上限"),
    SERIAL_DELAY("Delay", "ディレイ"),
    SERIAL_DELAY_TIP("Serial communication processing each of standby time (ms)", "シリアル通信処理毎の待機時間(ms)"),
    SERIAL_START_CODE("Start Code", "開始コード"),
    SERIAL_START_CODE_TIP("Serial start code", "シリアル開始コード"),
    SERIAL_END_CODE("End Code", "終了コード"),
    SERIAL_END_CODE_TIP("Serial end code", "シリアル終了コード"),
    BACK_GROUND_FILE("Background File", "バックグラウンドファイル"),
    BACK_GROUND_FILE_TIP("Background file", "バックグラウンドファイル"),
    BACK_GROUND_FILE_BROWSE("Browse", "参照"),
    BACK_GROUND_FILE_BROWSE_TIP("Browse background file", "バックグラウンドファイルの参照"),
    EXTERNAL_SUBPROGRAM_DIRECTORY("External SubProgram Directory", "外部サブプログラムディレクトリ"),
    EXTERNAL_SUBPROGRAM_DIRECTORY_TIP("External SubProgram Directory", "外部サブプログラムディレクトリ"),
    EXTERNAL_SUBPROGRAM_DIRECTORY_BROWSE("Browse", "参照"),
    EXTERNAL_SUBPROGRAM_DIRECTORY_BROWSE_TIP("Browse external sub-program directory", "外部サブプログラムディレクトリの参照"),
    GCODE_GROUP("G Code Group", "Gコードグループ"),
    GCODE_GROUP0("Group 0", "グループ0"),
    GCODE_GROUP1("Group 1", "グループ1"),
    GCODE_GROUP2("Group 2", "グループ2"),
    GCODE_GROUP3("Group 3", "グループ3"),
    GCODE_GROUP4("Group 4", "グループ4"),
    GCODE_GROUP5("Group 5", "グループ5"),
    GCODE_GROUP6("Group 6", "グループ6"),
    GCODE_GROUP7("Group 7", "グループ7"),
    GCODE_GROUP8("Group 8", "グループ8"),
    GCODE_GROUP9("Group 9", "グループ9"),
    GCODE_GROUP10("Group 10", "グループ10"),
    GCODE_GROUP11("Group 11", "グループ11"),
    GCODE_GROUP12("Group 12", "グループ12"),
    GCODE_GROUP13("Group 13", "グループ13"),
    GCODE_GROUP14("Group 14", "グループ14"),
    GCODE_GROUP15("Group 15", "グループ15"),
    GCODE_GROUP16("Group 16", "グループ16"),
    GCODE_GROUP17("Group 17", "グループ17"),
    GCODE_GROUP18("Group 18", "グループ18"),
    GCODE_GROUP19("Group 19", "グループ19"),
    GCODE_GROUP20("Group 20", "グループ20"),
    GCODE_GROUP21("Group 21", "グループ21"),
    GCODE_GROUP22("Group 22", "グループ22"),
    GCODE_GROUP23("Group 23", "グループ23"),
    GCODE_GROUP24("Group 24", "グループ24"),
    GCODE_GROUP25("Group 25", "グループ25"),
    GCODE_GROUP26("Group 26", "グループ26"),
    GCODE_GROUP27("Group 27", "グループ27"),
    GCODE_GROUP28("Group 28", "グループ28"),
    GCODE_GROUP29("Group 29", "グループ29"),
    GCODE_GROUP30("Group 30", "グループ30"),
    GCODE_GROUP_TIP("Group setting of the G code\n | delimited\n @ The initial value\n ※ only run in a virtual machine\nex) @0 | 1 | 2 | 3", "Gコードのグループ設定\n |は区切り\n @は初期値\n※仮想マシン内でのみ実行\nex) @0 | 1 | 2 | 3"),
    CODE_CHANGE("Code Change", "コード変換"),
    CODE_CHANGE_PROGRAM_CALL("Program Call", "プログラム呼出"),
    CODE_CHANGE_PROGRAM_CALL_TIP("Pre-conversion program number = conversion after the program number\n※ it only affects the output of the virtual machine\nex) O1000 = O2000\n    O1000 = TEST", "変換前プログラム番号 = 変換後プログラム番号\n※仮想マシンの出力にのみ影響\nex) O1000 = O2000\n    O1000 = TEST"),
    CODE_CHANGE_G("G Code", "Gコード"),
    CODE_CHANGE_M("M Code", "Mコード"),
    CODE_CHANGE_T("T Code", "Tコード"),
    CODE_CHANGE_D("D Code", "Dコード"),
    CODE_CHANGE_H("H Code", "Hコード"),
    CODE_CHANGE_TIP("Before conversion code number = conversion after the code number or string\n | delimited\n※ suppress the output by the value after conversion to minus\n※ it only affects the output of the virtual machine\nex) 100.0 = -1\nex) 100.0 = 101 | (TEST)", "変換前コード番号 = 変換後コード番号又は文字列\n |は区切り\n※変換後の値をマイナスにすることで出力を抑制する\n※仮想マシンの出力にのみ影響\nex) 100.0 = -1\nex) 100.0 = 101 | (TEST)"),
    MACRO_CALL("Macro Call", "マクロ呼出"),
    MACRO_CALL_G("G Code", "Gコード"),
    MACRO_CALL_M("M Code", "Mコード"),
    MACRO_CALL_TIP("Code number = call program number\nex) 100 = O1000\n    100 = TEST\n※ only run in a virtual machine", "コード番号 = 呼出プログラム番号\nex) 100 = O1000\n    100 = TEST\n※仮想マシン内でのみ実行"),
    COORDINATE("Coordinate", "座標"),
    COORDINATE_X("X"),
    COORDINATE_Y("Y"),
    COORDINATE_Z("Z"),
    COORDINATE_A("A"),
    COORDINATE_B("B"),
    COORDINATE_C("C"),
    COORDINATE_U("U"),
    COORDINATE_V("V"),
    COORDINATE_W("W"),
    ORIGIN("Mechanical Origin", "機械原点"),
    ORIGIN_TIP("G-code output, output, including the mechanical origin\n※ it only affects the output of the virtual machine", "Gコード出力時、機械原点を含めて出力\n※仮想マシンの出力にのみ影響"),
    EXTERNAL("External", "外部"),
    EXTERNAL_TIP("G-code output, the output including the external coordinate system\n※ it only affects the output of the virtual machine", "Gコード出力時、外部座標系を含めて出力\n※仮想マシンの出力にのみ影響"),
    G92("G92"),
    G92_TIP("G-code output, output, including the G92 coordinate system\n※ it only affects the output of the virtual machine", "Gコード出力時、G92座標系を含めて出力\n※仮想マシンの出力にのみ影響"),
    TOOL("Tool", "工具"),
    TOOL_TIP("G-code output, output, including the tool offset\n※ it only affects the output of the virtual machine", "Gコード出力時、工具オフセットを含めて出力\n※仮想マシンの出力にのみ影響"),
    MIRROR("Mirror", "ミラー"),
    MIRROR_TIP("G-code output, output, including the mirror coordinate\n※ it only affects the output of the virtual machine", "Gコード出力時、ミラー座標を含めて出力\n※仮想マシンの出力にのみ影響"),
    LADDER("Ladder", "ラダー"),
    LADDER_SEQUENCE_CODE("Sequence Code", "シーケンスコード"),
    LADDER_PREPARATORY_CODE("Preparatory Code", "準備コード"),
    LADDER_DIMENSION_CODE("Dimension Code", "寸法コード"),
    LADDER_AUXILIARY_CODE("Auxiliary Code", "補助コード"),
    LADDER_FEEDRATE_CODE("Feedrate Code", "送り速度コード"),
    LADDER_SPINDLE_CODE("Spindle Code", "スピンドル"),
    LADDER_TOOL_CODE("Tool Code", "工具コード"),
    LADDER_N("N"),
    LADDER_G("G"),
    LADDER_X("X"),
    LADDER_Y("Y"),
    LADDER_Z("Z"),
    LADDER_A("A"),
    LADDER_B("B"),
    LADDER_C("C"),
    LADDER_U("U"),
    LADDER_V("V"),
    LADDER_W("W"),
    LADDER_M("M"),
    LADDER_R("R"),
    LADDER_I("I"),
    LADDER_J("J"),
    LADDER_K("K"),
    LADDER_F("F"),
    LADDER_S("S"),
    LADDER_T("T"),
    LADDER1_TIP("Address to output as instruction value to ladder", "ラダーへ指令値として出力するアドレス"),
    LADDER2_TIP("Address to be input as return value from ladder", "ラダーから戻り値として入力するアドレス"),
    G54("G54"),
    G54_TIP("G-code output, output, including the G54 coordinate system\n※ it only affects the output of the virtual machine", "Gコード出力時、G54座標系を含めて出力\n※仮想マシンの出力にのみ影響"),
    G55("G55"),
    G55_TIP("G-code output, output, including the G55 coordinate system\n※ it only affects the output of the virtual machine", "Gコード出力時、G55座標系を含めて出力\n※仮想マシンの出力にのみ影響"),
    G56("G56"),
    G56_TIP("G-code output, output, including the G56 coordinate system\n※ it only affects the output of the virtual machine", "Gコード出力時、G56座標系を含めて出力\n※仮想マシンの出力にのみ影響"),
    G57("G57"),
    G57_TIP("G-code output, output, including the G57 coordinate system\n※ it only affects the output of the virtual machine", "Gコード出力時、G57座標系を含めて出力\n※仮想マシンの出力にのみ影響"),
    G58("G58"),
    G58_TIP("G-code output, output, including the G58 coordinate system\n※ it only affects the output of the virtual machine", "Gコード出力時、G58座標系を含めて出力\n※仮想マシンの出力にのみ影響"),
    G59("G59"),
    G59_TIP("G-code output, output, including the G59 coordinate system\n※ it only affects the output of the virtual machine", "Gコード出力時、G59座標系を含めて出力\n※仮想マシンの出力にのみ影響"),
    COORDINATE_X_TIP("X coordinate value\n※ only run in a virtual machine", "X座標値\n※仮想マシン内でのみ実行"),
    COORDINATE_Y_TIP("Y coordinate value\n※ only run in a virtual machine", "Y座標値\n※仮想マシン内でのみ実行"),
    COORDINATE_Z_TIP("Z coordinate value\n※ only run in a virtual machine", "Z座標値\n※仮想マシン内でのみ実行"),
    COORDINATE_A_TIP("A coordinate value\n※ only run in a virtual machine", "A座標値\n※仮想マシン内でのみ実行"),
    COORDINATE_B_TIP("B coordinate value\n※ only run in a virtual machine", "B座標値\n※仮想マシン内でのみ実行"),
    COORDINATE_C_TIP("C coordinate value\n※ only run in a virtual machine", "C座標値\n※仮想マシン内でのみ実行"),
    COORDINATE_U_TIP("U coordinate value\n※ only run in a virtual machine", "U座標値\n※仮想マシン内でのみ実行"),
    COORDINATE_V_TIP("V coordinate value\n※ only run in a virtual machine", "V座標値\n※仮想マシン内でのみ実行"),
    COORDINATE_W_TIP("W coordinate value\n※ only run in a virtual machine", "W座標値\n※仮想マシン内でのみ実行"),
    TOOL_OFFSET("Tool Offset", "工具補正"),
    TOOL_OFFSET_TIP("Tool number = tool compensation amount\nTool number = wear correction amount | shape correction amount\nTool number = wear correction amount (H code) | shape correction amount (H code) | wear correction amount (D code) | shape correction amount (D code)\n | Delimited\n※ only run in a virtual machine\nex) 1 = 100.000\nex) 1 = 105.123 | 100.000 | 0.000 | 0.000", "工具番号 = 工具補正量\n工具番号 = 磨耗補正量 | 形状補正量\n工具番号 = 磨耗補正量(Hコード) | 形状補正量(Hコード) | 磨耗補正量(Dコード) | 形状補正量(Dコード)\n |は区切り\n※仮想マシン内でのみ実行\nex) 1 = 100.000\nex) 1 = 105.123 | 100.000 | 0.000 | 0.000"),
    VARIABLES("Variables", "変数"),
    VARIABLES_TIP("Variable number = value\nVariable number = value | variable name\n※ only run in a virtual machine\nex) 3101 = 3.141592653 | _PI", "変数番号 = 値\n変数番号 = 値 | 変数名\n※仮想マシン内でのみ実行\nex) 3101 = 3.141592653 | _PI"),
    TOOL_CHANGE("Tool Change", "工具交換"),
    TOOL_CHANGE_PROGRAM_CHECK("Tool Change Program Call", "工具交換時プログラム呼出"),
    TOOL_CHANGE_PROGRAM_CHECK_TIP("Tool change when the program call\n※ it only affects the output of the virtual machine", "工具交換時プログラム呼出\n※仮想マシンの出力にのみ影響"),
    TOOL_CHANGE_XY_CHECK("Includes XY", "XYを含める"),
    TOOL_CHANGE_XY_CHECK_TIP("Include the XY to tool change when the program call\n※ it only affects the output of the virtual machine", "工具交換時プログラム呼出にXYを含める\n※仮想マシンの出力にのみ影響"),
    TOOL_CHANGE_PROGRAM("Program Number", "プログラム番号"),
    TOOL_CHANGE_PROGRAM_TIP("Program number\nex) O1000\n    TEST\n※ it only affects the output of the virtual machine", "プログラム番号\nex) O1000\n    TEST\n※仮想マシンの出力にのみ影響"),
    TOOL_CHANGE_MCODE_CHECK("Enable Tool Change M Code", "工具交換Mコード有"),
    TOOL_CHANGE_MCODE_CHECK_TIP("Enable tool change M code\n※ it only affects the output of the virtual machine", "工具交換Mコード有\n※仮想マシンの出力にのみ影響"),
    TOOL_CHANGE_MCODE("M code number", "Mコード番号"),
    TOOL_CHANGE_MCODE_TIP("M code number\n※ it only affects the output of the virtual machine", "Mコード番号\n※仮想マシンの出力にのみ影響"),
    SKIP_FUNCTION("Skip Function", "スキップ機能"),
    SKIP_FUNCTION_PROGRAM_CHECK("Skip Function Program Call", "スキップ機能時プログラム呼出"),
    SKIP_FUNCTION_PROGRAM_CHECK_TIP("Skip function when the program call※ it only affects the output of the virtual machine", "スキップ機能時プログラム呼出\n※仮想マシンの出力にのみ影響"),
    SKIP_FUNCTION_PROGRAM("Program Number", "プログラム番号"),
    SKIP_FUNCTION_PROGRAM_TIP("Program number\nex) O1000\n    TEST\n※ it only affects the output of the virtual machine", "プログラム番号\nex) O1000\n    TEST\n※仮想マシンの出力にのみ影響"),
    OPTION("Option", "オプション"),
    OPTION_OPTIMIZATION("Optimization", "最適化"),
    OPTION_OPTIMIZATION_TIP("Optimization\n※ it only affects the output of the virtual machine", "最適化\n※仮想マシンの出力にのみ影響"),
    OPTION_EXCOMMENT("Expanded Comments", "拡張コメント"),
    OPTION_EXCOMMENT_TIP("(MSG,***) output a *** to the console\n(PRINT,***) output *** to the serial/file\n(NOTIFY,***) notify the *** to javascript\n(JS,***) run the javascript of ***\nM198 ??? (PATH,***) external file path = ***\n※ it only affects the output of the virtual machine", "(MSG,***)***をコンソールに出力\n(PRINT,***)***をシリアル/ファイルに出力\n(NOTIFY,***)***をjavascriptに通知\n(JS,***)***のjavascriptを実行\nM198 ??? (PATH,***)***=外部ファイルパス\n※仮想マシンの出力にのみ影響"),
    OPTION_DISABLE_30033004("Disable #3003 And #3004", "#3003,#3004を出力しない"),
    OPTION_DISABLE_30033004_TIP("Disable #3003 And #3004\n※ it only affects the output of the virtual machine", "#3003,#3004を無効\n※仮想マシンの出力にのみ影響"),
    OPTION_REPLACE_3006M0("Replace #3006 To M0", "#3006をM0に置換"),
    OPTION_REPLACE_3006M0_TIP("Replace #3006 To M0\n※ it only affects the output of the virtual machine", "#3006をM0に置換\n※仮想マシンの出力にのみ影響"),
    OPTION_ONLY_S("M3 Added When S Instruction Only", "S指令のみ時M3追加"),
    OPTION_ONLY_S_TIP("M3 Added When S Instruction Only\n※ it only affects the output of the virtual machine", "S指令のみ時M3追加\n※仮想マシンの出力にのみ影響"),
    OPTION_RS274NGC("RS274/NGC"),
    OPTION_RS274NGC_TIP("RS274 / Next Generation Controller\n※ it only affects the output of the virtual machine", "RS274 / Next Generation Controller\n※仮想マシンの出力にのみ影響"),
    OPTION_DEBUG_JSON("Debug JSON", "デバッグ JSON"),
    OPTION_DEBUG_JSON_TIP("JSON format of the file output\n※ it only affects the output of the debug", "JSON形式のファイル出力\n※デバッグの出力にのみ影響"),
    OPTION_MAX_FEED_RATE("Maximum Feed Rate", "最大送り速度"),
    OPTION_MAX_FEED_RATE_TIP("Tool number = maximum feed rate\n※ it only affects the output of the virtual machine\nex) 93 = 300", "工具番号 = 最大送り速度\n※仮想マシンの出力にのみ影響\nex) 93 = 300"),
    OPTION_MAX_REVOLUTION("Maximum Revolutions", "最大回転数"),
    OPTION_MAX_REVOLUTION_TIP("Tool number = maximum revolutions\n※ it only affects the output of the virtual machine\nex) 93 = 1500", "工具番号 = 最大回転数\n※仮想マシンの出力にのみ影響\nex) 93 = 1500"),
    OPTION_START_PROGRAM("Start Execution", "開始時実行"),
    OPTION_START_PROGRAM_TIP("G-code to be executed at the beginning of the program\n※ only run in a virtual machine", "プログラムの開始時に実行するGコード\n※仮想マシン内でのみ実行"),
    OPTION_BLOCK_PROGRAM("Block Execution", "ブロック毎実行"),
    OPTION_BLOCK_PROGRAM_TIP("G code to be executed for each block\n※ only run in a virtual machine", "ブロック毎に実行するGコード\n※仮想マシン内でのみ実行"),
    OPTION_END_PROGRAM("End Execution", "終了時実行"),
    OPTION_END_PROGRAM_TIP("G code to be executed at the end\n※ only run in a virtual machine", "終了時に実行するGコード\n※仮想マシン内でのみ実行"),
    ERROR_CODE_CHANGE_PROGRAM_CALL("Code Change Program Call", "コード変換 プログラム呼出"),
    ERROR_CODE_CHANGE_G("Code Change G Code", "コード変換 Gコード"),
    ERROR_CODE_CHANGE_M("Code Change M Code", "コード変換 Mコード"),
    ERROR_CODE_CHANGE_T("Code Change T Code", "コード変換 Tコード"),
    ERROR_CODE_CHANGE_D("Code Change D Code", "コード変換 Dコード"),
    ERROR_CODE_CHANGE_H("Code Change H Code", "コード変換 Hコード"),
    ERROR_MACRO_CALL_G("Macro Call G Code", "マクロ呼出 Gコード"),
    ERROR_MACRO_CALL_M("Macro Call M Code", "マクロ呼出 Mコード"),
    ERROR_TOOL_OFFSET("Tool Offset", "工具補正"),
    ERROR_VARIABLES("Variables", "変数"),
    ERROR_LADDER("Ladder", "ラダー"),
    ERROR_OPTION_MAX_FEED_RATE("Option Maximum Feed Rate", "オプション 最大送り速度"),
    ERROR_OPTION_MAX_REVOLUTION("Option Maximum Revolutions", "オプション 最大回転数"),
    PARSER_NOT_COMPATIBLE("The parser is not compatible", "構文解析ツールの互換性がありません"),
    FILE_NOT_FOUND("File Not Found", "ファイルが見つかりません"),
    FILE_CAN_NOT_READ("File Can Not Read", "ファイルを読み取ることができません"),
    FILE_CAN_NOT_WRITE("File Can Not Write", "ファイルに書き込むことができません"),
    FILE_NOT_FILE("File is Not File", "ファイルはファイルではありません"),
    FILE_NOT_DIRECTORY("File is Not Directory", "ファイルはディレクトリではありません"),
    MULTIPLE_SELECTION_DISABLED("Multiple Selection Disabled", "複数選択不可"),
    SAVE_CHANGE_PROGRAM("Save Changes Program?", "プログラムの変更内容を保存しますか？"),
    ABNORMAL_END("Abnormal End", "異常終了"),
    ERROR_END("Error End", "エラー終了"),
    GCODE_FX("GcodeFX"),
    GCODE("Gcode"),
    BYTECODE("ByteCode"),
    ALGORITHM("Blowfish"),
    VERSION("Version"),
    GBC_COMPLETION("Completion gbc", "gbc 完了"),
    GBC_FAILED("Failed gbc", "gbc 失敗");

    private int lang_ = 0;
    private final String[] text_ = new String[2];

    private DesignEnums(final String message) {
        for (int i = 0; i < text_.length; i++) {
            text_[i] = message;
        }
    }

    private DesignEnums(final String en, final String ja) {
        text_[0] = en;
        text_[1] = ja;
    }

    public void setLang(int l) {
        lang_ = l;
    }

    @Override
    public String toString() {
        return text_[lang_];
    }
}
